export const mails = [
    {
        from: 'ashi@cmail.com',
        to: 'fala@lo.com',
        subject: 'test mail 1 :This is a test body 1',
        body: 'This is a test body 1',
        year: '2020',
        month: 'Apr',
        date: '30',
        time: '23:48',
        file: false,
        datetime: new Date('2020-04-30')
    },
    {
        from: 'bshi@cmail.com',
        to: 'sala@lo.com',
        subject: 'Big promotion happend on this up coming weekend',
        body: 'Big promotion happend on this up coming weekend',
        year: '2020',
        month: 'May',
        date: '02',
        time: '12:55',
        file: false,
        datetime: new Date('2020-05-02')
    },
    {
        from: 'cishi@cmail.com',
        to: 'gala@lo.com',
        subject: 'Join our new service for premium regular customer',
        body: 'Join our new service for premium regular customer',
        year: '2020',
        month: 'May',
        date: '17',
        time: '11:48',
        file: false,
        datetime: new Date('2020-05-17')
    },
    {
        from: 'dishi@cmail.com',
        to: 'lala@lo.com',
        subject: 'ID:235256668 Your order has been shipped from akita city',
        body: 'This is a test body 1',
        year: '2020',
        month: 'May',
        date: '11',
        time: '02:00',
        file: false,
        datetime: new Date('2020-05-11')
    },
    {
        from: 'eishi@cmail.com',
        to: 'jala@lo.com',
        subject: 'ID:235256668 Your order has been shipped from akita city',
        body: 'This is a test body 1',
        year: '2020',
        month: 'May',
        date: '08',
        time: '22:48',
        file: false,
        datetime: new Date('2020-05-08')
    },
    {
        from: 'fishi@cmail.com',
        to: 'lala@lo.com',
        subject: 'ID:235256668 Your order has been shipped from akita city',
        body: 'This is a test body 1',
        year: '2020',
        month: 'Apr',
        date: '28',
        time: '06:25',
        file: false,
        datetime: new Date('2020-04-28')
    },
    {
        from: 'gishi@cmail.com',
        to: 'hala@lo.com',
        subject: 'ID:235256668 Your order has been shipped from akita city',
        body: 'This is a test body 1',
        year: '2020',
        month: 'May',
        date: '15',
        time: '0:30',
        file: false,
        datetime: new Date('2020-05-15')
    },
    {
        from: 'hishi@cmail.com',
        to: 'lala@lo.com',
        subject: 'ID:235256668 Your order has been shipped from akita city',
        body: 'This is a test body 1',
        year: '2020',
        month: 'May',
        date: '26',
        time: '00:20',
        file: false,
        datetime: new Date('2020-05-26')
    },
    {
        from: 'ishi@cmail.com',
        to: 'oala@lo.com',
        subject: 'ID:235256668 Your order has been shipped from akita city',
        body: 'This is a test body 1',
        year: '2020',
        month: 'May',
        date: '11',
        time: '21:43',
        file: false,
        datetime: new Date('2020-05-11')
    },{
        from: 'jishi@cmail.com',
        to: 'lala@lo.com',
        subject: 'ID:235256668 Your order has been shipped from akita city',
        body: 'This is a test body 1',
        year: '2020',
        month: 'May',
        date: '24',
        time: '23:07',
        file: false,
        datetime: new Date('2020-05-24')
    },
    {
        from: 'kishi@cmail.com',
        to: 'lala@lo.com',
        subject: 'Reason why cats getting popular than dog',
        body: 'This is a test body 1',
        year: '2020',
        month: 'May',
        date: '23',
        time: '17:25',
        file: false,
        datetime: new Date('2020-05-23')
    },
    {
        from: 'lishi@cmail.com',
        to: 'vala@lo.com',
        subject: 'ID:235256668 Your order has been shipped from akita city',
        body: 'This is a test body 1',
        year: '2020',
        month: 'Jun',
        date: '01',
        time: '10:30',
        file: false,
        datetime: new Date('2020-06-01')
    },
    {
        from: 'aishi@cmail.com',
        to: 'dakaala@lo.com',
        subject: 'ID:235256668 Your order has been shipped from akita city',
        body: 'This is a test body 1',
        year: '2020',
        month: 'Apr',
        date: '20',
        time: '15:48',
        file: false,
        datetime: new Date('2020-04-20')
    },
    {
        from: 'vishi@cmail.com',
        to: 'qla@lo.com',
        subject: 'If you want your app to work offline and load faster....',
        body: 'This is a test body 1',
        year: '2020',
        month: 'May',
        date: '01',
        time: '11:44',
        file: false,
        datetime: new Date('2020-05-01')
    },
    {
        from: 'oishi@cmail.com',
        to: 'uala@lo.com',
        subject: 'Learn more about our service in 3min turtorial',
        body: 'This is a test body 1',
        year: '2020',
        month: 'May',
        date: '19',
        time: '09:12',
        file: false,
        datetime: new Date('2020-05-19')
    },
    {
        from: 'nishi@cmail.com',
        to: 'mala@lo.com',
        subject: 'Check it out as soon as possible',
        body: 'This is a test body 1',
        year: '2020',
        month: 'May',
        date: '27',
        time: '07:56',
        file: false,
        datetime: new Date('2020-05-27')
    },
    {
        from: 'qishi@cmail.com',
        to: 'dala@lo.com',
        subject: 'mail error code:644',
        body: 'This is a test body 1',
        year: '2020',
        month: 'May',
        date: '28',
        time: '08:18',
        file: false,
        datetime: new Date('2020-05-28')
    },
    {
        from: 'eishi@cmail.com',
        to: 'esla@lo.com',
        subject: 'ID:235256668 Your order has been shipped from akita city',
        body: 'This is a test body 1',
        year: '2020',
        month: 'May',
        date: '12',
        time: '20:39',
        file: false,
        datetime: new Date('2020-05-12')
    },
    {
        from: 'wishi@cmail.com',
        to: 'waala@lo.com',
        subject: 'ID:235256668 Your order has been shipped from akita city',
        body: 'This is a test body 1',
        year: '2020',
        month: 'Apr',
        date: '03',
        time: '00:08',
        file: false,
        datetime: new Date('2020-04-03')
    },
    {
        from: 'uishi@cmail.com',
        to: 'pala@lo.com',
        subject: 'ID:235256668 Your order has been shipped from akita city',
        body: 'This is a test body 1',
        year: '2020',
        month: 'May',
        date: '03',
        time: '13:33',
        file: false,
        datetime: new Date('2020-05-03')
    },
]